using ExaminationSystem.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace ExaminationSystem.DTOs.ExamDTOs;

public class CreateExamDTO
{
    public string Title { get; set; } = null!;
    public ExamTypes Types { get; set; }
    public int NumberOfQuestions { get; set; }
    public bool IsAutoGenerated { get; set; }
    public int DurationInMinutes { get; set; }
    public int CourseID { get; set; }
}
