using ExaminationSystem.DTOs.CourseDTOs;
using ExaminationSystem.Models.Enums;

namespace ExaminationSystem.DTOs.ExamDTOs;

public class ExamDetailsDTO
{
    public int ExamID { get; set; }
    public string Title { get; set; } = null!;
    public ExamTypes Types { get; set; }
    public int NumberOfQuestions { get; set; }
    public bool IsAutoGenerated { get; set; }
    public int DurationInMinutes { get; set; }
    public GetCourseInfoDTO CourseInfo { get; set; } 
}
