using ExaminationSystem.DTOs.ExamDTOs;
using ExaminationSystem.Services;
using ExaminationSystem.ViewModels.ExamViewModels;
using Microsoft.AspNetCore.Mvc;

namespace ExaminationSystem.Controllers;

[ApiController]
[Route("[Controller]/[Action]")]
public class ExamsController: ControllerBase
{
    ExamService _examService;
    public ExamsController()
    {
        _examService = new ExamService();
    }

    //Add Course
    [HttpPost]
    public async Task<ActionResult> AddExamAsync(CreateExamViewModel vm)
    {
        if (!ModelState.IsValid)
            return BadRequest(ModelState);

        var dto = new CreateExamDTO
        {
            Title = vm.Title,
            Types = vm.Types,
            DurationInMinutes = vm.DurationInMinutes,
            NumberOfQuestions = vm.NumberOfQuestions,
            IsAutoGenerated = vm.IsAutoGenerated,
            CourseID = vm.CourseID
        };

        var result = await _examService.AddExamAsync(dto);

        if (result == null) return BadRequest();

        return StatusCode(StatusCodes.Status201Created, result);
    }

    [HttpGet]
    public IEnumerable<ExamDetailsViewModel> GetAllExams()
    {
        return _examService.GetAllExams()
            .Select(m => new ExamDetailsViewModel
            {
                ExamID = m.ExamID,
                Title = m.Title,
                Types = m.Types,
                DurationInMinutes = m.DurationInMinutes,
                NumberOfQuestions = m.NumberOfQuestions,
                IsAutoGenerated = m.IsAutoGenerated,
                CourseInfo = m.CourseInfo
            });
    }

    [HttpGet("{id}")]
    public async Task<ActionResult> GetExamByIDAsync(int id)
    {

        var dto = await _examService.GetExamByIDAsync(id);

        if (dto == null)
            return BadRequest();

        return Ok(new ExamDetailsViewModel
        {
            ExamID = dto.ExamID,
            Title = dto.Title,
            Types = dto.Types,
            DurationInMinutes = dto.DurationInMinutes,
            IsAutoGenerated = dto.IsAutoGenerated,
            NumberOfQuestions = dto.NumberOfQuestions,
            CourseInfo = dto.CourseInfo
        });
    }

    [HttpPut("{id}")]
    public async Task<ActionResult<ExamDetailsViewModel>> UpdateExamAsync(int id, UpdateExamViewModel vm)
    {
        if (!ModelState.IsValid)
            return BadRequest(ModelState);

        var dto = await _examService.UpdateExamAsync(id, new UpdateExamDTO
        {
            Title = vm.Title,
            Types = vm.Types,
            DurationInMinutes = vm.DurationInMinutes,
            NumberOfQuestions = vm.NumberOfQuestions,
            IsAutoGenerated = vm.IsAutoGenerated,
            CourseID = vm.CourseID
        });

        if (dto == null)
            return BadRequest();

        return Ok(new ExamDetailsViewModel
        {
            ExamID = dto.ExamID,
            Title = dto.Title,
            NumberOfQuestions = dto.NumberOfQuestions,
            DurationInMinutes = dto.DurationInMinutes,
            Types = dto.Types,
            IsAutoGenerated = dto.IsAutoGenerated,
            CourseInfo = dto.CourseInfo
        });
    }

    [HttpDelete("{id}")]
    public async Task DeleteExamHardAsync(int id)
    {
        await _examService.DeleteExamAsync(id);
    }

    [HttpPost]
    public async Task AssignQuestionsToExamAsync(AssignQuestionsToExamViewModel vm) 
    {
        await _examService.AssignQuestionsToExamAsync(new AssignQuestionsToExamDTO 
        {
            ExamID = vm.ExamID,
            QuestionIDs = vm.QuestionIDs
        });
    }
}
