using ExaminationSystem.DTOs.CourseDTOs;
using ExaminationSystem.DTOs.ExamDTOs;
using ExaminationSystem.Models;
using ExaminationSystem.Repositories.Implementations;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Services;

public class ExamService
{
    BaseRepository<Exam> _examRepo;
    BaseRepository<Course> _courseRepo;
    BaseRepository<ExamQuestion> _examQuestionRepo;
    public ExamService()
    {
        _examRepo = new BaseRepository<Exam>();
        _courseRepo = new BaseRepository<Course>();
        _examQuestionRepo = new BaseRepository<ExamQuestion>();
    }

    public async Task<ExamDetailsDTO> AddExamAsync(CreateExamDTO dto)
    {
        var course = await _courseRepo.GetByIdAsync(dto.CourseID);

        if (course == null)
            throw new Exception($"No course was found with ID = {dto.CourseID}");

        Exam exam = new Exam
        {
            Title = dto.Title,
            IsAutoGenerated = dto.IsAutoGenerated,
            NumberOfQuestions = dto.NumberOfQuestions,
            DurationInMinutes = dto.DurationInMinutes,
            Types = dto.Types,
            CourseID = dto.CourseID
        };

        var result = await _examRepo.CreateAsync(exam);

        return new ExamDetailsDTO
        {
            Title = result.Title,
            DurationInMinutes = result.DurationInMinutes,
            NumberOfQuestions = result.NumberOfQuestions,
            Types = result.Types,
            IsAutoGenerated = result.IsAutoGenerated,
            CourseInfo = new GetCourseInfoDTO
            {
                CourseID = result.CourseID,
                Name = course.Name
            }
        };
    }

    public IEnumerable<ExamDetailsDTO> GetAllExams()
    {
        return _examRepo.GetAll().Select(e => new ExamDetailsDTO
        {
            ExamID = e.ID,
            Title = e.Title,
            Types = e.Types,
            NumberOfQuestions = e.NumberOfQuestions,
            DurationInMinutes = e.DurationInMinutes,
            IsAutoGenerated = e.IsAutoGenerated,
            CourseInfo = new GetCourseInfoDTO
            {
                CourseID = e.Course.ID,
                Name = e.Course.Name
            }
        }).OrderBy(e => e.CourseInfo.Name).ToList();
    }

    public async Task<ExamDetailsDTO> GetExamByIDAsync(int id)
    {
        var exam = await _examRepo.GetByIdAsync(id);

        if (exam == null)
            throw new Exception($"No exam was found with ID = {id}");

        var course = await _courseRepo.GetByIdAsync(exam.CourseID);

        return new ExamDetailsDTO
        {
            ExamID = exam.ID,
            Title = exam.Title,
            Types = exam.Types,
            DurationInMinutes = exam.DurationInMinutes,
            IsAutoGenerated = exam.IsAutoGenerated,
            NumberOfQuestions = exam.NumberOfQuestions,
            CourseInfo = new GetCourseInfoDTO
            {
                CourseID = course.ID,
                Name = course.Name
            }
        };
    }

    public async Task<ExamDetailsDTO> UpdateExamAsync(int examID, UpdateExamDTO dto)
    {
        var result = await _examRepo.UpdateAsync(
        c => c.ID == examID,
        s => s
              .SetProperty(d => d.Title, dto.Title)
              .SetProperty(d => d.Types, dto.Types)
              .SetProperty(d => d.IsAutoGenerated, dto.IsAutoGenerated)
              .SetProperty(d => d.DurationInMinutes, dto.DurationInMinutes)
              .SetProperty(d => d.NumberOfQuestions, dto.NumberOfQuestions)
              .SetProperty(d => d.UpdatedAt, DateTime.UtcNow)
        );

        if (result == 0)
            throw new Exception("Update failed");

        return await GetExamByIDAsync(examID);
    }

    public async Task DeleteExamAsync(int id)
    {
        var exam = await _examRepo.GetByIdAsync(id);

        if (exam == null)
            throw new Exception($"No exam was found with ID = {id}");

        await _examRepo.DeleteAsync(exam);
    }

    //Assign Questions to Exam
    public async Task AssignQuestionsToExamAsync(AssignQuestionsToExamDTO dto)
    {
        var exam = await _examRepo.GetByIdAsync(dto.ExamID);

        if (exam == null)
            throw new Exception($"No exam was found with ID = {dto.ExamID}");

        var NumberOfQuestionsAdded = await _examQuestionRepo.GetAll(m => m.ExamID == dto.ExamID).CountAsync();

        if (dto.QuestionIDs.Count() > exam.NumberOfQuestions || 
            dto.QuestionIDs.Count > (exam.NumberOfQuestions - NumberOfQuestionsAdded))
            throw new Exception("Can't Add All This Questions");

        foreach (var questionID in dto.QuestionIDs)
        {
            bool IsAlreadyAssigned = await _examQuestionRepo.AnyAsync(eq => eq.QuestionID == questionID);

            if (IsAlreadyAssigned)
                continue;

            await _examQuestionRepo.CreateAsync(new ExamQuestion { QuestionID = questionID ,ExamID = dto.ExamID});
        }
    }

    //TODO:Assign Question to Exam

    //TODO:UnAssign Question to Exam

}
