using AutoMapper;
using AutoMapper.QueryableExtensions;
using ExaminationSystem.DTOs.ExamDTOs;
using ExaminationSystem.Models;
using ExaminationSystem.Repositories.Implementations;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Services;

public class ExamService
{
    BaseRepository<Exam> _examRepo;
    BaseRepository<Course> _courseRepo;
    BaseRepository<ExamQuestion> _examQuestionRepo;
    IMapper _mapper;
    public ExamService(IMapper mapper)
    {
        _examRepo = new BaseRepository<Exam>();
        _courseRepo = new BaseRepository<Course>();
        _examQuestionRepo = new BaseRepository<ExamQuestion>();
        _mapper = mapper;
    }

    public async Task<ExamDetailsDTO> AddExamAsync(CreateExamDTO dto)
    {
        var course = await _courseRepo.GetByIdAsync(dto.CourseID);

        if (course == null)
            throw new Exception($"No course was found with ID = {dto.CourseID}");

        var exam = _mapper.Map<Exam>(dto);

        await _examRepo.AddAsync(exam);

        exam.Course = course;

        var examDetails = _mapper.Map<ExamDetailsDTO>(exam);

        return examDetails;
    }

    public IEnumerable<ExamDetailsDTO> GetAllExams()
    {
        var examList = _examRepo.GetAll().ProjectTo<ExamDetailsDTO>(_mapper.ConfigurationProvider).ToList();

        return examList;
    }

    public async Task<ExamDetailsDTO> GetExamByIDAsync(int id)
    {
        var exam = await _examRepo.GetByIdAsync(id,m => m.Course);

        if (exam == null)
            throw new Exception($"No exam was found with ID = {id}");

        var examDetails = _mapper.Map<ExamDetailsDTO>(exam);

        return examDetails;
    }

    public async Task<ExamDetailsDTO> UpdateExamAsync(int examID, UpdateExamDTO dto)
    {
        var result = await _examRepo.UpdateAsync(
        c => c.ID == examID,
        s => s
              .SetProperty(d => d.Title, dto.Title)
              .SetProperty(d => d.Types, dto.Types)
              .SetProperty(d => d.IsAutoGenerated, dto.IsAutoGenerated)
              .SetProperty(d => d.DurationInMinutes, dto.DurationInMinutes)
              .SetProperty(d => d.NumberOfQuestions, dto.NumberOfQuestions)
              .SetProperty(d => d.UpdatedAt, DateTime.UtcNow)
        );

        if (result == 0)
            throw new Exception("Update failed");

        return await GetExamByIDAsync(examID);
    }

    public async Task DeleteExamAsync(int id)
    {
        var exam = await _examRepo.GetByIdAsync(id);

        if (exam == null)
            throw new Exception($"No exam was found with ID = {id}");

        await _examRepo.DeleteAsync(exam);
    }

    //Assign Questions to Exam Manully
    public async Task AssignQuestionsToExamManuallyAsync(AssignQuestionsToExamDTO dto)
    {
        var exam = await _examRepo.GetByIdAsync(dto.ExamID);

        if (exam == null)
            throw new Exception($"No exam was found with ID = {dto.ExamID}");

        var NumberOfQuestionsAdded = await _examQuestionRepo.GetAll(m => m.ExamID == dto.ExamID).CountAsync();

        if (dto.QuestionIDs.Count() > exam.NumberOfQuestions || 
            dto.QuestionIDs.Count > (exam.NumberOfQuestions - NumberOfQuestionsAdded))
            throw new Exception("Can't Add All This Questions");

        foreach (var questionID in dto.QuestionIDs)
        {
            bool IsAlreadyAssigned = await _examQuestionRepo.AnyAsync(eq => eq.QuestionID == questionID);

            if (IsAlreadyAssigned)
                continue;

            await _examQuestionRepo.AddAsync(new ExamQuestion { QuestionID = questionID ,ExamID = dto.ExamID});
        }
    }

    //TODO:Assign Questions to Exam Auto


}
