using AutoMapper;
using AutoMapper.QueryableExtensions;
using ExaminationSystem.DTOs.ExamDTOs;
using ExaminationSystem.Models;
using ExaminationSystem.Repositories.Implementations;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Services;

public class ExamService
{
    BaseRepository<Exam> _examRepo;
    BaseRepository<ExamQuestion> _examQuestionRepo;
    BaseRepository<Question> _questionRepo;
    IMapper _mapper;
    public ExamService(IMapper mapper)
    {
        _examRepo = new BaseRepository<Exam>();
        _examQuestionRepo = new BaseRepository<ExamQuestion>();
        _questionRepo = new BaseRepository<Question>();
        _mapper = mapper;
    }

    public async Task<ExamDetailsDTO> AddExamAsync(CreateExamDTO dto, int instructorID)
    {
        var exam = _mapper.Map<Exam>(dto);
        exam.CreatedBy = instructorID;

        await _examRepo.AddAsync(exam);

        var examDetails = _mapper.Map<ExamDetailsDTO>(exam);

        return examDetails;
    }

    public async Task<IEnumerable<ExamDetailsDTO>> GetAllExamsAsync(int instructorID)
    {
        var exams = await _examRepo.GetAll().Where(m => m.CreatedBy == instructorID)
            .ProjectTo<ExamDetailsDTO>(_mapper.ConfigurationProvider).ToListAsync();

        if (!exams.Any())
            throw new Exception("Not found any exams");

        return exams;
    }

    public async Task<ExamDetailsDTO> GetExamByIDAsync(int id, int instructorID)
    {
        var exam = await _examRepo.GetByIdAsync(id,m => m.Course);

        if (exam == null)
            throw new Exception($"No exam was found with ID = {id}");

        if (exam.CreatedBy != instructorID)
            throw new UnauthorizedAccessException("You can not view this exam");

        var examDetails = _mapper.Map<ExamDetailsDTO>(exam);

        return examDetails;
    }

    public async Task<ExamDetailsDTO> UpdateExamAsync(int examID,int instructorID, UpdateExamDTO dto)
    {
        var exam = await _examRepo.GetByIdAsync(examID);

        if (exam == null)
            throw new Exception($"Not found exam with ID {examID}");

        if (exam.CreatedBy != instructorID)
            throw new UnauthorizedAccessException("You can not modfiy this exam");

        if (exam.CourseID != null)
            throw new Exception("You cannot modify this exam because it already assigned to course.");

        var result = await _examRepo.UpdateAsync(
        c => c.ID == examID,
        s => s
              .SetProperty(d => d.Title, dto.Title)
              .SetProperty(d => d.Types, dto.Types)
              .SetProperty(d => d.IsAutoGenerated, dto.IsAutoGenerated)
              .SetProperty(d => d.DurationInMinutes, dto.DurationInMinutes)
              .SetProperty(d => d.NumberOfQuestions, dto.NumberOfQuestions)
              .SetProperty(d => d.UpdatedAt, DateTime.UtcNow)
              .SetProperty(d => d.UpdatedBy, instructorID)
        );

        if (result == 0)
            throw new Exception("Update failed");

        var newExam = await _examRepo.GetByIdAsync(examID);

        var examDetailsDto = _mapper.Map<ExamDetailsDTO>(newExam); 

        return examDetailsDto;
    }

    public async Task DeleteExamAsync(int id,int instructorID)
    {
        var exam = await _examRepo.GetByIdAsync(id);

        if (exam == null)
            throw new Exception($"No exam was found with ID = {id}");

        if (exam.CreatedBy != instructorID)
            throw new UnauthorizedAccessException("You can not delete this exam");

        await _examRepo.DeleteAsync(exam);
    }



}
