using ExaminationSystem.Models.Enums;

namespace ExaminationSystem.ViewModels.ExamViewModels;

public class CreateExamViewModel
{
    public string Title { get; set; } = null!;
    public ExamTypes Types { get; set; }
    public int NumberOfQuestions { get; set; }
    public bool IsAutoGenerated { get; set; }
    public int DurationInMinutes { get; set; }

}
