using ExaminationSystem.DTOs.CourseDTOs;

namespace ExaminationSystem.ViewModels.ExamViewModels;

public class ExamDetailsViewModel
{
    public int ExamID { get; set; }
    public string Title { get; set; } = null!;
    public ExamTypes Types { get; set; }
    public int NumberOfQuestions { get; set; }
    public bool IsAutoGenerated { get; set; }
    public int DurationInMinutes { get; set; }
    public GetCourseInfoDTO CourseInfo { get; set; }

}
