using System.ComponentModel.DataAnnotations;

namespace ExaminationSystem.ViewModels.ExamViewModels;

public class UpdateExamViewModel
{
    [Required]
    [StringLength(150, ErrorMessage = "Max length is 150 character")]
    [MinLength(2, ErrorMessage = "Minimem length is 2 character")]
    public string Title { get; set; } = null!;

    [Required]
    [EnumDataType(typeof(ExamTypes), ErrorMessage = "Type of Exam is not correct")]
    public ExamTypes Types { get; set; }

    [Range(1, 1000, ErrorMessage = "Number of questions must be between 1 to 1000")]
    public int NumberOfQuestions { get; set; }
    public bool IsAutoGenerated { get; set; }

    [Range(2, 500)]
    public int DurationInMinutes { get; set; }
}
