using AutoMapper.QueryableExtensions;
using ExaminationSystem.DTOs.ExamDTOs;

namespace ExaminationSystem.Services.Implementation;

public class ExamService : IExamService
{
    private readonly IBaseRepository<Exam> _examRepo;
    private readonly IMapper _mapper;
    public ExamService(
        IMapper mapper,
        IBaseRepository<Exam> examRepo)
    {
        _examRepo = examRepo;
        _mapper = mapper;
    }

    public async Task<ResponseDTO<IEnumerable<ExamDetailsDTO>>> GetAllExamsAsync(int instructorID)
    {
        var exams = await _examRepo.GetAll().Where(m => m.CreatedBy == instructorID)
            .ProjectTo<ExamDetailsDTO>(_mapper.ConfigurationProvider).ToListAsync();

        if (!exams.Any())
            return new FailureResponseDTO<IEnumerable<ExamDetailsDTO>>(ErrorCode.ExamNotFound, "Not found any exams");

        return new SuccessResponseDTO<IEnumerable<ExamDetailsDTO>>(exams);
    }

    public async Task<ResponseDTO<ExamDetailsDTO>> GetExamByIDAsync(int examID, int instructorID)
    {
        var exam = await _examRepo.GetById(examID).Include(m => m.Course).FirstOrDefaultAsync();

        if (exam == null)
            return new FailureResponseDTO<ExamDetailsDTO>(ErrorCode.InvalidExamID, $"No exam was found with ID = {examID}");

        if (exam.CreatedBy != instructorID)
            return new FailureResponseDTO<ExamDetailsDTO>(ErrorCode.UnAuthorized, "You can not view this exam");

        var examDetails = _mapper.Map<ExamDetailsDTO>(exam);

        return new SuccessResponseDTO<ExamDetailsDTO>(examDetails);
    }

    public async Task<ResponseDTO<ExamDetailsDTO>> UpdateExamAsync(int examID,int instructorID, UpdateExamDTO dto)
    {
        var exam = await _examRepo.GetById(examID).FirstOrDefaultAsync();

        if (exam == null)
            return new FailureResponseDTO<ExamDetailsDTO>(ErrorCode.InvalidExamID, $"Not found exam with ID {examID}");

        if (exam.CreatedBy != instructorID)
            return new FailureResponseDTO<ExamDetailsDTO>(ErrorCode.UnAuthorized, "You can not modfiy this exam");

        if (exam.CourseID != null)
            return new FailureResponseDTO<ExamDetailsDTO>(ErrorCode.ExamAlreadyAssignedToCourse, "You cannot modify this exam because it already assigned to course.");

        //var result = await _examRepo.UpdateAsync(
        //c => c.ID == examID,
        //s => s
        //      .SetProperty(d => d.Title, dto.Title)
        //      .SetProperty(d => d.Types, dto.Types)
        //      .SetProperty(d => d.IsAutoGenerated, dto.IsAutoGenerated)
        //      .SetProperty(d => d.DurationInMinutes, dto.DurationInMinutes)
        //      .SetProperty(d => d.NumberOfQuestions, dto.NumberOfQuestions)
        //      .SetProperty(d => d.UpdatedAt, DateTime.UtcNow)
        //      .SetProperty(d => d.UpdatedBy, instructorID)
        //);

        //if (result == 0)
        //    return new FailureResponseDTO<ExamDetailsDTO>(ErrorCode.FailedUpdateExam, "Update failed");

        var newExam = await _examRepo.GetById(examID).FirstOrDefaultAsync();

        var examDetailsDto = _mapper.Map<ExamDetailsDTO>(newExam); 

        return new SuccessResponseDTO<ExamDetailsDTO>(examDetailsDto);
    }

    public async Task DeleteExamAsync(int id,int instructorID)
    {
        var exam = await _examRepo.GetById(id).FirstOrDefaultAsync();

        if (exam == null)
            throw new Exception($"No exam was found with ID = {id}");

        if (exam.CreatedBy != instructorID)
            throw new UnauthorizedAccessException("You can not delete this exam");

        await _examRepo.HardDeleteAsync(exam);
    }



}
