using ExaminationSystem.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace ExaminationSystem.Models;

public class Exam : BaseModel
{
    [Required]
    [MaxLength(150)]
    public string Title { get; set; } = null!;
    public ExamTypes Types { get; set; }
    public int NumberOfQuestions { get; set; }
    public bool IsAutoGenerated { get; set; }
    public int DurationInMinutes { get; set; }

    [Required]
    public int CourseID { get; set; }
    public Course Course { get; set; }

    public ICollection<Question> Questions { get; set; } = new List<Question>();

    public ICollection<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>();
}
