using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ExaminationSystem.Migrations
{
    /// <inheritdoc />
    public partial class updateExamsTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "Exams");

            migrationBuilder.DropColumn(
                name: "NumberOfQuestions",
                table: "Exams");

            migrationBuilder.RenameColumn(
                name: "Types",
                table: "Exams",
                newName: "Type");

            migrationBuilder.AddColumn<TimeOnly>(
                name: "EndTime",
                table: "Exams",
                type: "time",
                nullable: false,
                defaultValue: new TimeOnly(0, 0, 0));

            migrationBuilder.AddColumn<TimeOnly>(
                name: "StartTime",
                table: "Exams",
                type: "time",
                nullable: false,
                defaultValue: new TimeOnly(0, 0, 0));

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "ID",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 4, 29, 8, 48, 47, 202, DateTimeKind.Utc).AddTicks(5007));

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "ID",
                keyValue: 2,
                column: "CreatedAt",
                value: new DateTime(2026, 4, 29, 8, 48, 47, 202, DateTimeKind.Utc).AddTicks(5011));

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "ID",
                keyValue: 3,
                column: "CreatedAt",
                value: new DateTime(2026, 4, 29, 8, 48, 47, 202, DateTimeKind.Utc).AddTicks(5012));
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "EndTime",
                table: "Exams");

            migrationBuilder.DropColumn(
                name: "StartTime",
                table: "Exams");

            migrationBuilder.RenameColumn(
                name: "Type",
                table: "Exams",
                newName: "Types");

            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "Exams",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<int>(
                name: "NumberOfQuestions",
                table: "Exams",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "ID",
                keyValue: 1,
                column: "CreatedAt",
                value: new DateTime(2026, 4, 17, 17, 10, 34, 312, DateTimeKind.Utc).AddTicks(1544));

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "ID",
                keyValue: 2,
                column: "CreatedAt",
                value: new DateTime(2026, 4, 17, 17, 10, 34, 312, DateTimeKind.Utc).AddTicks(1548));

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "ID",
                keyValue: 3,
                column: "CreatedAt",
                value: new DateTime(2026, 4, 17, 17, 10, 34, 312, DateTimeKind.Utc).AddTicks(1549));
        }
    }
}
