using ExaminationSystem.DTOs.InstructorDTOs;

namespace ExaminationSystem.DTOs.IntructorDTOs;

public class InstructorDtoProfile : Profile
{
    public InstructorDtoProfile()
    {
        CreateMap<Instructor, GetInstructorInfoDTO>()
            .ForMember(dest => dest.FullName, opt => opt.MapFrom(src => $"{src.User.FirstName} {src.User.LastName}"));

        CreateMap<CreateExamManualDTO, Exam>()
            .ForMember(dest => dest.NumberOfQuestions, opt => opt.MapFrom(src => src.QuestionIDs.Count))
            .ForMember(dest => dest.IsAutoGenerated, opt => opt.MapFrom( _=> false))
            .ForMember(dest => dest.ExamQuestions, opt => opt.MapFrom(src => src.QuestionIDs.Select(qid => new ExamQuestion {QuestionID = qid}).ToList()));

        CreateMap<CreateExamAutoDTO, Exam>()
            .ForMember(dest => dest.IsAutoGenerated, opt => opt.MapFrom(_ => true));

    }
}
